# docker-compose.yml
version: '3.3'
services:
  jenkins_ci: # nombre q le colocamos
    container_name: jenkins_ci
    image: jenkins/jenkins:alpine
    user: root
    hostname: jenkins
    environment:
      MY_NAME: "David_devops"
      JAVA_OPTS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
      SONARQUBE_HOST: sonarqube
    ports: 
      - "8585:8080"
      - "50000:50000"
    volumes: 
      - /c/home/David-devops/data-storage/jenkins/var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - net_devops
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
  sonarqube:  # nombre q le colocamos
    container_name: sonarqube
    image: sonarqube:8.9.5-community
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"
    networks: 
      - net_devops
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/extensions:/opt/sonarqube/extensions
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3072M
  networks:
    net_devops:
      driver: bridge
      name: net_devops

  nexus:
    container_name: nexus
    image: sonatype/nexus3
    hostname: nexus
    restart: always
    ports: 
      - 8081:8081
    volumes:
      - /c/home/David-devops/data-storage/nexus/nexus-data:/nexus-data